# mautrix-signal config (v0.26+ megabridge format)

homeserver:
  address: http://localhost:8008
  domain: matrix.example.net
  software: standard
  async_media: false

appservice:
  address: http://localhost:29328
  hostname: 127.0.0.1
  port: 29328
  id: signal
  as_token: REDACTED_2d40a4b8
  hs_token: REDACTED_5a8da637
  bot:
    username: signalbot
    displayname: Signal Bridge Bot
    avatar: mxc://maunium.net/wPJgTQbZOtpBFLDCwwNgHWgq

database:
  type: postgres
  uri: postgres://mautrix_signal:mautrix_signal_pass@localhost:5432/mautrix_signal?sslmode=disable
  max_open_conns: 5

bridge:
  command_prefix: "!signal"
  personal_filtering_spaces: true
  private_chat_portal_meta: true
  bridge_matrix_leave: false
  bridge_notices: false
  permissions:
    "*": relay
    "matrix.example.net": user
    "@dominicus:matrix.example.net": admin

network:
  displayname_template: '{{or .ContactName .ProfileName .PhoneNumber "Unknown user"}}'
  use_contact_avatars: true
  use_outdated_profiles: true
  sync_contacts_on_startup: true
  number_in_topic: true
  device_name: mautrix-signal

encryption:
  allow: true
  default: true
  require: false
  appservice: true
  msc4190: true
  pickle_key: REDACTED_28ece096

logging:
  min_level: info
  writers:
    - type: stdout
      format: pretty-colored
