#!/usr/bin/env python3
"""
Sync From Device - Pull current config and create Merge Request
Handles the Device → GitLab flow for emergency/manual changes

Usage: sync_from_device.py <device_type> <device_name>
"""
import sys
import os
import yaml
import subprocess
from pathlib import Path
from datetime import datetime
from netmiko import ConnectHandler

def get_live_config(device_name, device_type):
    """Fetch current running-config from device"""
    
    username = os.getenv('CISCO_USER', 'kyriakosp')
    password = os.getenv('CISCO_PASSWORD')
    
    if not password:
        print("ERROR: CISCO_PASSWORD not set")
        return None
    
    if device_type == 'Firewall':
        device_type_netmiko = 'cisco_asa'
    else:
        device_type_netmiko = 'cisco_ios'
    
    device = {
        'device_type': device_type_netmiko,
        'host': f"{device_name}.example.net",
        'username': username,
        'password': password,
        'timeout': 60,
    }
    
    print(f"Connecting to {device_name}...")
    try:
        conn = ConnectHandler(**device)
        print(f"Fetching running-config...")
        running_config = conn.send_command("show running-config")
        conn.disconnect()
        print(f"✓ Retrieved {len(running_config.splitlines())} lines")
        return running_config
    except Exception as e:
        print(f"ERROR: Failed to connect: {str(e)}")
        return None

def detect_changes(gitlab_config_path, live_config):
    """
    Compare GitLab config vs live config
    Returns: (has_changes, diff_summary)
    """
    if not gitlab_config_path.exists():
        return True, "Config file doesn't exist in GitLab (new device)"
    
    with open(gitlab_config_path) as f:
        gitlab_config = f.read()
    
    # Quick check
    if gitlab_config.strip() == live_config.strip():
        return False, "No changes detected"
    
    # Generate diff summary
    import difflib
    
    gitlab_lines = gitlab_config.splitlines(keepends=True)
    live_lines = live_config.splitlines(keepends=True)
    
    diff = list(difflib.unified_diff(
        gitlab_lines,
        live_lines,
        fromfile='gitlab',
        tofile='device',
        lineterm=''
    ))
    
    additions = sum(1 for line in diff if line.startswith('+') and not line.startswith('+++'))
    deletions = sum(1 for line in diff if line.startswith('-') and not line.startswith('---'))
    
    return True, f"{additions} additions, {deletions} deletions"

def create_merge_request(device_type, device_name, diff_summary):
    """
    Create GitLab merge request with the changes
    Uses GitLab API
    """
    gitlab_url = os.getenv('CI_SERVER_URL', 'https://gitlab.example.net')
    project_id = os.getenv('CI_PROJECT_ID')
    gitlab_token = os.getenv('GITLAB_TOKEN')
    
    if not gitlab_token:
        print("WARNING: GITLAB_TOKEN not set, cannot create MR automatically")
        print("You'll need to create the MR manually")
        return None
    
    import requests
    
    # Create branch name
    timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
    branch_name = f"sync-from-device/{device_name}-{timestamp}"
    
    # Get current branch SHA
    api_url = f"{gitlab_url}/api/v4"
    headers = {'PRIVATE-TOKEN': gitlab_token}
    
    # Create branch
    print(f"Creating branch: {branch_name}")
    response = requests.post(
        f"{api_url}/projects/{project_id}/repository/branches",
        headers=headers,
        json={
            'branch': branch_name,
            'ref': 'main'
        }
    )
    
    if response.status_code != 201:
        print(f"ERROR: Failed to create branch: {response.text}")
        return None
    
    # Create MR
    print(f"Creating merge request...")
    mr_title = f"Sync from device: {device_name}"
    mr_description = f"""## Device Configuration Sync

**Device:** `{device_name}` ({device_type})
**Timestamp:** {datetime.now().isoformat()}
**Source:** Live device running-config

### Changes Detected
{diff_summary}

### Reason for Sync
This MR was created to synchronize GitLab with the current device configuration.
Possible reasons:
- Emergency changes made via SSH console
- Manual troubleshooting/debugging
- Configuration drift detected

### Review Checklist
- [ ] Verify changes are intentional
- [ ] Document reason for out-of-band changes
- [ ] Update any related documentation
- [ ] Ensure changes don't conflict with planned deployments

### Next Steps
1. Review the diff carefully
2. If changes are correct: Approve and merge
3. If changes are incorrect: Close MR and redeploy correct config
4. Document why out-of-band changes were necessary

---
*Auto-generated by sync_from_device.py*
"""
    
    response = requests.post(
        f"{api_url}/projects/{project_id}/merge_requests",
        headers=headers,
        json={
            'source_branch': branch_name,
            'target_branch': 'main',
            'title': mr_title,
            'description': mr_description,
            'REDACTED_dae379fc': True,
            'labels': ['sync-from-device', 'drift-detected']
        }
    )
    
    if response.status_code == 201:
        mr_data = response.json()
        mr_url = mr_data['web_url']
        print(f"✓ Merge request created: {mr_url}")
        return mr_url
    else:
        print(f"ERROR: Failed to create MR: {response.text}")
        return None

def sync_from_device(device_type, device_name):
    """Main sync function"""
    
    print("=" * 70)
    print(f"SYNC FROM DEVICE: {device_name}")
    print("=" * 70)
    print()
    
    # Paths
    config_path = Path(f"network/configs/{device_type}/{device_name}")
    
    # Step 1: Fetch live config
    print("[1/5] Fetching live configuration from device...")
    live_config = get_live_config(device_name, device_type)
    
    if not live_config:
        print("ERROR: Failed to fetch config from device")
        return 1
    
    print()
    
    # Step 2: Detect changes
    print("[2/5] Comparing with GitLab config...")
    has_changes, diff_summary = detect_changes(config_path, live_config)
    
    print(f"   {diff_summary}")
    print()
    
    if not has_changes:
        print("✓ GitLab is already in sync with device")
        print("   No action needed")
        return 0
    
    # Step 3: Show preview
    print("[3/5] Changes detected:")
    print()
    
    if config_path.exists():
        with open(config_path) as f:
            gitlab_config = f.read()
        
        # Show first 20 lines of diff
        import difflib
        diff = list(difflib.unified_diff(
            gitlab_config.splitlines(keepends=True),
            live_config.splitlines(keepends=True),
            fromfile='gitlab',
            tofile='device',
            lineterm=''
        ))
        
        print("Diff preview (first 20 lines):")
        for line in diff[:20]:
            print(line.rstrip())
        
        if len(diff) > 20:
            print(f"... and {len(diff) - 20} more lines")
    
    print()
    
    # Step 4: Update local file
    print("[4/5] Updating local GitLab config file...")
    config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(config_path, 'w') as f:
        f.write(live_config)
    
    print(f"   ✓ Updated: {config_path}")
    print()
    
    # Step 5: Create MR or commit
    print("[5/5] Creating merge request...")
    
    if os.getenv('CI'):
        # Running in GitLab CI - create MR via API
        mr_url = create_merge_request(device_type, device_name, diff_summary)
        if mr_url:
            print()
            print("=" * 70)
            print("✓ SYNC COMPLETE")
            print("=" * 70)
            print(f"Merge Request: {mr_url}")
            print()
            print("Next steps:")
            print("  1. Review the MR")
            print("  2. Approve and merge if changes are correct")
            print("  3. Document why manual changes were made")
        else:
            print("WARNING: Could not create MR automatically")
            print("You'll need to commit and push manually")
    else:
        # Running locally - commit to branch
        timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
        branch_name = f"sync-from-device/{device_name}-{timestamp}"
        
        print(f"Creating branch: {branch_name}")
        subprocess.run(['git', 'checkout', '-b', branch_name], check=True)
        subprocess.run(['git', 'add', str(config_path)], check=True)
        subprocess.run([
            'git', 'commit', '-m', 
            f"Sync from device: {device_name}\n\n{diff_summary}"
        ], check=True)
        
        print()
        print("=" * 70)
        print("✓ SYNC COMPLETE")
        print("=" * 70)
        print(f"Branch created: {branch_name}")
        print()
        print("Next steps:")
        print(f"  1. Push: git push origin {branch_name}")
        print("  2. Create MR in GitLab UI")
        print("  3. Review and merge")
    
    return 0

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: sync_from_device.py <device_type> <device_name>")
        print()
        print("Examples:")
        print("  sync_from_device.py Router nl-lte01")
        print("  sync_from_device.py Switch nlsw01")
        print("  sync_from_device.py Firewall nlfw01")
        sys.exit(1)
    
    device_type = sys.argv[1]
    device_name = sys.argv[2]
    
    sys.exit(sync_from_device(device_type, device_name))