#!/usr/bin/env python3
"""
NAPALM-based configuration deployment with automatic rollback.

Replaces direct_deploy.py's raw Netmiko approach with NAPALM, which provides:
  - Atomic config merge with diff preview
  - Automatic rollback on failure (discard_config)
  - Consistent save behavior across platforms
  - Session logging

Usage:
    deploy.py <device_type> <device_name> <diff_json>

Example:
    deploy.py Router nlrtr01 artifacts/diffs/nlrtr01_diff.json

The diff_json must contain a "remediation_text" key (generated by v2/generate_diff.py).
Falls back to building remediation from "diff_blocks" if remediation_text is missing.
"""
import json
import os
import sys
import time
from datetime import datetime
from pathlib import Path
import napalm

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from lib.devices import (
    DeviceOS,
    build_profile,
    REDACTED_52c008dd,
    napalm_connection,
    netmiko_connection,
    READ_TIMEOUT,
)


def load_diff(diff_path):
    """Load and validate diff JSON."""
    path = Path(diff_path)
    if not path.exists():
        raise FileNotFoundError(f"Diff file not found: {diff_path}")

    data = json.loads(path.read_text())
    if not isinstance(data, dict):
        raise ValueError("Invalid diff file: not a dictionary")

    return data


def build_remediation_text(diff_data):
    """Extract or build remediation config text from diff data."""
    # Prefer the flat remediation text (generated by v2/generate_diff.py)
    if diff_data.get("remediation_text"):
        return diff_data["remediation_text"]

    # Fallback: reconstruct from diff_blocks (compat with v1 generate_diff.py)
    blocks = diff_data.get("diff_blocks", [])
    if not blocks:
        return ""

    lines = []
    for block in blocks:
        parents = block.get("parents", [])
        cmds = block.get("lines", [])
        for parent in parents:
            lines.append(parent)
        for cmd in cmds:
            if parents:
                lines.append(f"  {cmd}")
            else:
                lines.append(cmd)

    return "\n".join(lines)


ASA_ERROR_PATTERNS = [
    "ERROR:",
    "Invalid input detected",
    "Incomplete command",
    "% Ambiguous command",
    "No matching command found",
    "not valid",
    "not allowed",
    "ERROR: % Invalid",
    "object not found",
    "Unable to",
    "access-list compiled error",
]


def _detect_asa_errors(output: str) -> list[str]:
    """Check Netmiko output for ASA error indicators."""
    errors = []
    for line in output.splitlines():
        stripped = line.strip()
        if any(pattern.lower() in stripped.lower() for pattern in ASA_ERROR_PATTERNS):
            errors.append(stripped)
    return errors


def _rollback_asa(conn, backup_config: str, profile_name: str):
    """
    Rollback ASA to the pre-deployment config.

    Strategy: push the full pre-deploy config back via Netmiko.
    This is a best-effort rollback — if the device is in a broken state,
    manual intervention via console may be needed.
    """
    print()
    print("=" * 70)
    print("ROLLING BACK ASA CONFIG")
    print("=" * 70)
    print()

    try:
        # Clear the current candidate by exiting config mode
        conn.exit_config_mode()

        # Re-enter config mode and push the backup config line by line.
        # Filter to only configuration commands (skip headers, prompts, etc.)
        rollback_lines = []
        in_config = False
        for line in backup_config.splitlines():
            stripped = line.rstrip()
            # Skip ASA metadata headers
            if stripped.startswith(":") or stripped.startswith("ASA Version"):
                continue
            if stripped.startswith("!"):
                continue
            if not stripped:
                continue
            # Skip dynamic content that shouldn't be pushed
            if any(
                skip in stripped.lower()
                for skip in [
                    "cryptochecksum",
                    "last configuration",
                    "building configuration",
                    "current configuration",
                ]
            ):
                continue
            rollback_lines.append(stripped)

        if not rollback_lines:
            print("   WARNING: No rollback commands extracted from backup")
            return False

        print(f"   Pushing {len(rollback_lines)} rollback commands...")
        output = conn.send_config_set(
            rollback_lines, exit_config_mode=True, cmd_verify=False
        )

        errors = _detect_asa_errors(output)
        if errors:
            print(f"   WARNING: {len(errors)} errors during rollback:")
            for err in errors[:5]:
                print(f"     {err}")
            print("   Rollback may be incomplete — check device manually")
            return False

        # Save the rolled-back config
        save_out = conn.send_command("write memory", read_timeout=READ_TIMEOUT)
        print(f"   Saved: {save_out.strip()}")
        print("   Rollback complete")
        return True

    except Exception as e:
        print(f"   ROLLBACK FAILED: {e}")
        print("   Manual intervention required via console")
        return False


def deploy_asa(profile, diff_data, remediation):
    """Deploy configuration to ASA/AP device using Netmiko.

    NAPALM's IOS driver cannot handle ASA prompts (or AP TCL limitations),
    so we use Netmiko directly with:
      - Pre-deployment backup (for rollback)
      - Per-command error detection
      - Automatic rollback on error
      - write memory to save
    """
    os.makedirs("backups", exist_ok=True)
    timestamp = int(time.time())
    backup_file = f"backups/{profile.name}_pre_deploy_{timestamp}.cfg"
    post_backup = f"backups/{profile.name}_post_deploy_{timestamp}.cfg"

    with netmiko_connection(profile) as conn:
        print(f"   Connected to {profile.name} (Netmiko)")
        print()

        # [3/6] Pre-deployment backup
        print("[3/6] Backing up current configuration...")
        running = conn.send_command("show running-config", read_timeout=READ_TIMEOUT)
        with open(backup_file, "w") as f:
            f.write(f"! Backup: {profile.name}\n")
            f.write(f"! Type: pre-deployment (Netmiko)\n")
            f.write(f"! Timestamp: {datetime.now().isoformat()}\n")
            f.write(f"!\n")
            f.write(running)
        print(f"   Backup saved: {backup_file}")
        print()

        # [4/6] Apply config with error detection
        print("[4/6] Applying configuration via Netmiko...")
        commands = [line for line in remediation.splitlines() if line.strip()]
        print(f"   Commands to apply: {len(commands)}")
        for cmd in commands[:10]:
            print(f"     {cmd}")
        if len(commands) > 10:
            print(f"     ... and {len(commands) - 10} more")
        print()

        output = conn.send_config_set(commands, cmd_verify=False)

        # Check for errors in the output
        errors = _detect_asa_errors(output)
        if errors:
            print(f"   ERROR: {len(errors)} command(s) failed:")
            for err in errors:
                print(f"     {err}")
            print()
            print("   Initiating rollback...")
            rollback_ok = _rollback_asa(conn, running, profile.name)
            if rollback_ok:
                print("   Rolled back to pre-deploy state")
            else:
                print(f"   Manual recovery needed from: {backup_file}")
            return 1

        print(f"   Applied {len(commands)} commands — no errors detected")
        if output.strip():
            # Show last few lines of output for visibility
            out_lines = [l for l in output.splitlines() if l.strip()]
            for line in out_lines[-5:]:
                print(f"     {line}")
        print()

        # [5/6] Save config
        print("[5/6] Saving configuration (write memory)...")
        save_output = conn.send_command_timing(
            "write memory", read_timeout=READ_TIMEOUT
        )
        print(f"   {save_output.strip()}")
        print()

        # [6/6] Post-deployment verification
        print("[6/6] Post-deployment verification...")
        post_running = conn.send_command(
            "show running-config", read_timeout=READ_TIMEOUT
        )
        with open(post_backup, "w") as f:
            f.write(post_running)

        print(f"   Device responsive: {profile.name}")
        print(f"   Post-backup: {post_backup}")

    print()
    print("=" * 70)
    print("SUCCESS: Deployment completed (Netmiko)")
    print("=" * 70)
    print(f"Pre-backup:  {backup_file}")
    print(f"Post-backup: {post_backup}")
    print(f"Commands applied: {len(commands)}")
    print()
    return 0


def deploy_napalm(profile, diff_data, remediation):
    """Deploy configuration to IOS/IOS-XE device using NAPALM merge."""
    os.makedirs("backups", exist_ok=True)
    timestamp = int(time.time())
    backup_file = f"backups/{profile.name}_pre_deploy_{timestamp}.cfg"

    with napalm_connection(profile) as device:
        print(f"   Connected to {profile.name} (NAPALM)")

        # Verify hostname
        facts = device.get_facts()
        print(f"   Hostname: {facts.get('hostname', 'unknown')}")
        print(f"   Model: {facts.get('model', 'unknown')}")
        print(f"   Uptime: {facts.get('uptime', 'unknown')}s")
        print()

        # [3/6] Create pre-deployment backup
        print("[3/6] Backing up current configuration...")
        running = device.get_config()["running"]
        with open(backup_file, "w") as f:
            f.write(f"! Backup: {profile.name}\n")
            f.write(f"! Type: pre-deployment (NAPALM)\n")
            f.write(f"! Timestamp: {datetime.now().isoformat()}\n")
            f.write(f"!\n")
            f.write(running)

        print(f"   Backup saved: {backup_file}")
        print()

        # [4/6] Load candidate config (merge mode, inline)
        print("[4/6] Loading candidate configuration (merge)...")
        device.load_merge_candidate(config=remediation)
        print("   Candidate loaded")

        # [5/6] Compare and commit
        print("[5/6] Comparing candidate vs running...")
        diff = device.compare_config()

        if not diff:
            print("   No differences found — config already matches intent")
            device.discard_config()
            print()
            print("SUCCESS: Device already at intended state (idempotent)")
            return 0

        print("   Diff:")
        for line in diff.splitlines()[:30]:
            print(f"     {line}")
        if len(diff.splitlines()) > 30:
            print(f"     ... and {len(diff.splitlines()) - 30} more lines")
        print()

        print("   Committing configuration...")
        device.commit_config()
        print("   Configuration committed and saved")
        print()

        # [6/6] Post-deployment verification
        print("[6/6] Post-deployment verification...")
        post_backup = f"backups/{profile.name}_post_deploy_{timestamp}.cfg"
        post_running = device.get_config()["running"]
        with open(post_backup, "w") as f:
            f.write(post_running)

        post_facts = device.get_facts()
        print(f"   Device responsive: hostname={post_facts.get('hostname')}")
        print(f"   Post-backup: {post_backup}")

        interfaces = device.get_interfaces()
        up_count = sum(1 for iface in interfaces.values() if iface["is_up"])
        total = len(interfaces)
        print(f"   Interfaces: {up_count}/{total} up")

    print()
    print("=" * 70)
    print("SUCCESS: Deployment completed")
    print("=" * 70)
    print(f"Pre-backup:  {backup_file}")
    print(f"Post-backup: {post_backup}")
    print(f"Diff blocks applied: {len(diff_data.get('diff_blocks', []))}")
    print()
    return 0


def deploy(device_type, device_name, diff_path):
    """Deploy configuration — NAPALM for IOS, Netmiko for ASA."""
    profile = build_profile(device_type, device_name)

    print("=" * 70)
    print(f"DEPLOYMENT: {device_name}")
    print(f"Device Type: {device_type}")
    print(f"OS: {profile.os.value}")
    print(f"Diff File: {diff_path}")
    print("=" * 70)
    print()

    # [1/6] Load diff
    print("[1/6] Loading deployment configuration...")
    diff_data = load_diff(diff_path)
    remediation = build_remediation_text(diff_data)

    if not remediation.strip():
        print("   No configuration changes to apply")
        print()
        print("SUCCESS: No changes needed")
        return 0

    print(f"   Remediation: {len(remediation.splitlines())} lines")
    print()

    # Show preview
    print("REMEDIATION PREVIEW:")
    print("-" * 70)
    for line in remediation.splitlines()[:20]:
        print(f"  {line}")
    if len(remediation.splitlines()) > 20:
        print(f"  ... and {len(remediation.splitlines()) - 20} more lines")
    print("-" * 70)
    print()

    # [2/6] Connect
    print("[2/6] Connecting...")

    try:
        if profile.use_napalm:
            return deploy_napalm(profile, diff_data, remediation)
        else:
            # ASA (prompt incompatible with NAPALM) and Access-Points
            # (no TCL for NAPALM inline transfer) use Netmiko direct.
            return deploy_asa(profile, diff_data, remediation)
    except Exception as e:
        print()
        print("=" * 70)
        print("DEPLOYMENT FAILED")
        print("=" * 70)
        print(f"Error: {e}")
        print()

        import traceback
        traceback.print_exc(file=sys.stderr)
        return 1


def main():
    if len(sys.argv) != 4:
        print("Usage: deploy.py <device_type> <device_name> <diff_json>")
        print()
        print("Example:")
        print("  deploy.py Router nlrtr01 artifacts/diffs/nlrtr01_diff.json")
        sys.exit(1)

    device_type = sys.argv[1]
    device_name = sys.argv[2]
    diff_path = sys.argv[3]

    valid_types = ["Router", "Switch", "Firewall", "Access-Point"]
    if device_type not in valid_types:
        print(f"ERROR: Invalid device type: {device_type}")
        sys.exit(1)

    exit_code = deploy(device_type, device_name, diff_path)
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
