---
version: 3

images:
  base_image:
    name: quay.io/ansible/creator-ee:latest

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'
  PKGMGR_PRESERVE_CACHE: 'always'

dependencies:
  python: |
    netmiko>=4.0.0
    paramiko>=3.0.0
    textfsm>=1.1.0
  galaxy: |
    collections:
      - name: cisco.ios
        version: ">=5.0.0"
      - name: cisco.asa
        version: ">=4.0.0"
      - name: ansible.netcommon
        version: ">=5.0.0"
  system: |
    git
    openssh-clients
    sshpass

additional_build_steps:
  prepend_final:
    - RUN pip3 install --upgrade pip