---
version: 3

build_arg_defaults:
  EE_BASE_IMAGE: quay.io/ansible/awx-ee:latest

dependencies:
  python: collections/requirements.txt
  galaxy: collections/requirements.yml

additional_build_steps:
  append_final:
    - RUN echo "Cisco EE built $(date)" > /etc/cisco-ee-version.txt