<?php
$CONFIG = array (
  'instanceid' => 'REDACTED',
  'passwordsalt' => 'REDACTED',
  'secret' => 'REDACTED',
  'davstorage.request_timeout' => 120,
  'REDACTED_b9f0d6dc' => 120,
  'REDACTED_33a6a8e6' => true,
  'session_lifetime' => 28800,
  'REDACTED_5ca8f535' => 57600,
  'session_keepalive' => true,
  'auto_logout' => false,
  'forwarded_for_headers' => 
  array (
    0 => 'X-Forwarded-For',
    1 => 'HTTP_X_FORWARDED_FOR',
  ),
  'trusted_proxies' => 
  array (
    0 => '10.0.X.X',
    1 => '10.0.X.X',
    3 => '10.0.X.X',
    4 => '10.0.X.X',
  ),
  'trusted_domains' => 
  array (
    0 => 'nextcloud.example.net',
    1 => 'nlnextcloud01.example.net',
    2 => '10.0.X.X',
    3 => 'nlnextcloud02.example.net',
    4 => '10.0.X.X',
    5 => 'nlnc01.example.net',
    6 => '10.0.X.X',
    7 => 'nlnc02.example.net',
    8 => '10.0.X.X',
    9 => 'nlhaproxy01.example.net',
    10 => '10.0.X.X',
    11 => 'nlhaproxy02.example.net',
    12 => '10.0.X.X',
    13 => 'nlnpm01.example.net',
    14 => '10.0.X.X',
    15 => 'grnpm01.example.net',
    16 => '10.0.X.X',
    17 => 'ankh.example.net',
    18 => '10.0.X.X',
    19 => '127.0.0.1',
  ),
  'datadirectory' => '/mnt/nextcloud-data',
  'dbtype' => 'mysql',
  'version' => '32.0.6.1',
  'overwrite.cli.url' => 'https://nextcloud.example.net',
  'dbname' => 'nextcloud',
  'dbhost' => 'proxysql.example.net:6033',
  'dbport' => '6033',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'REDACTED',
  'installed' => true,
  'maintenance' => false,
  'mail_domain' => 'mail.example.net',
  'mail_from_address' => 'nextcloud',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_smtphost' => 'smtp.example.net',
  'mail_smtpport' => '25',
  'REDACTED_3747706b' => 1,
  'REDACTED_b55449df' => 'NL',
  'default_locale' => 'nl_NL',
  'default_timezone' => 'Europe/Amsterdam',
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'allow_local_remote_servers' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\BMP',
    1 => 'OC\\Preview\\GIF',
    2 => 'OC\\Preview\\JPEG',
    3 => 'OC\\Preview\\Krita',
    4 => 'OC\\Preview\\MarkDown',
    5 => 'OC\\Preview\\MP3',
    6 => 'OC\\Preview\\OpenDocument',
    7 => 'OC\\Preview\\PNG',
    8 => 'OC\\Preview\\TXT',
    9 => 'OC\\Preview\\XBitmap',
    10 => 'OC\\Preview\\PDF',
    11 => 'OC\\Preview\\Movie',
  ),
  'REDACTED_08e8170a' => 'http://nlimaginary01.example.net:9000',
  'filelocking.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis.example.net',
    'port' => '6380',
    'dbindex' => 0,
    'timeout' => 5.0,
    'read_timeout' => 5.0,
  ),
  'auth.bruteforce.protection.enabled' => false,
  'ratelimit.protection.enabled' => false,
  'defaultapp' => 'dashboard,files',
  'facerecognition.external_model_url' => '10.0.X.X:5000',
  'facerecognition.external_model_api_key' => 'REDACTED',
  'theme' => '',
  'loglevel' => 2,
  'REDACTED_15210434' => 
  array (
  ),
);
